# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'api_frontend_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_API(object):
    def setupUi(self, API):
        API.setObjectName("API")
        API.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(API.sizePolicy().hasHeightForWidth())
        API.setSizePolicy(sizePolicy)
        API.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(API)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.vocabList = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.vocabList.sizePolicy().hasHeightForWidth())
        self.vocabList.setSizePolicy(sizePolicy)
        self.vocabList.setMinimumSize(QtCore.QSize(145, 200))
        self.vocabList.setWidgetResizable(True)
        self.vocabList.setObjectName("vocabList")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 183, 198))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.vocabList.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.vocabList, 1, 5, 2, 3)
        self.switchLanguageButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchLanguageButton.sizePolicy().hasHeightForWidth())
        self.switchLanguageButton.setSizePolicy(sizePolicy)
        self.switchLanguageButton.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.switchLanguageButton.setFont(font)
        self.switchLanguageButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/change.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.switchLanguageButton.setIcon(icon)
        self.switchLanguageButton.setIconSize(QtCore.QSize(16, 16))
        self.switchLanguageButton.setObjectName("switchLanguageButton")
        self.gridLayout.addWidget(self.switchLanguageButton, 3, 7, 1, 1)
        self.languageList = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageList.sizePolicy().hasHeightForWidth())
        self.languageList.setSizePolicy(sizePolicy)
        self.languageList.setMinimumSize(QtCore.QSize(0, 20))
        self.languageList.setObjectName("languageList")
        self.gridLayout.addWidget(self.languageList, 4, 5, 2, 3)
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBar.sizePolicy().hasHeightForWidth())
        self.searchBar.setSizePolicy(sizePolicy)
        self.searchBar.setObjectName("searchBar")
        self.gridLayout.addWidget(self.searchBar, 3, 5, 1, 2)
        self.language1Entry = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language1Entry.sizePolicy().hasHeightForWidth())
        self.language1Entry.setSizePolicy(sizePolicy)
        self.language1Entry.setMinimumSize(QtCore.QSize(0, 25))
        self.language1Entry.setObjectName("language1Entry")
        self.gridLayout.addWidget(self.language1Entry, 0, 3, 1, 1)
        self.language1Label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.language1Label.sizePolicy().hasHeightForWidth())
        self.language1Label.setSizePolicy(sizePolicy)
        self.language1Label.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.language1Label.setFont(font)
        self.language1Label.setObjectName("language1Label")
        self.gridLayout.addWidget(self.language1Label, 0, 0, 1, 3)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setIconSize(QtCore.QSize(32, 32))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 4, 2, 2, 1)
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addButton.setFont(font)
        self.addButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon2)
        self.addButton.setIconSize(QtCore.QSize(48, 48))
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 4, 0, 2, 1)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deleteButton.setFont(font)
        self.deleteButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon3)
        self.deleteButton.setIconSize(QtCore.QSize(48, 48))
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 4, 1, 2, 1)
        self.language2Entry = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language2Entry.sizePolicy().hasHeightForWidth())
        self.language2Entry.setSizePolicy(sizePolicy)
        self.language2Entry.setMinimumSize(QtCore.QSize(0, 25))
        self.language2Entry.setObjectName("language2Entry")
        self.gridLayout.addWidget(self.language2Entry, 1, 3, 1, 1)
        self.language2Label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.language2Label.sizePolicy().hasHeightForWidth())
        self.language2Label.setSizePolicy(sizePolicy)
        self.language2Label.setMinimumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.language2Label.setFont(font)
        self.language2Label.setObjectName("language2Label")
        self.gridLayout.addWidget(self.language2Label, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.vocabLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vocabLabel.sizePolicy().hasHeightForWidth())
        self.vocabLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.vocabLabel.setFont(font)
        self.vocabLabel.setObjectName("vocabLabel")
        self.gridLayout.addWidget(self.vocabLabel, 0, 5, 1, 2)
        self.informationLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.informationLabel.sizePolicy().hasHeightForWidth())
        self.informationLabel.setSizePolicy(sizePolicy)
        self.informationLabel.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.informationLabel.setFont(font)
        self.informationLabel.setTextFormat(QtCore.Qt.AutoText)
        self.informationLabel.setObjectName("informationLabel")
        self.gridLayout.addWidget(self.informationLabel, 2, 0, 1, 5)
        API.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(API)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        API.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(API)
        self.statusbar.setObjectName("statusbar")
        API.setStatusBar(self.statusbar)

        self.retranslateUi(API)
        QtCore.QMetaObject.connectSlotsByName(API)

    def retranslateUi(self, API):
        _translate = QtCore.QCoreApplication.translate
        API.setWindowTitle(_translate("API", "github.com/daspoet"))
        self.switchLanguageButton.setToolTip(_translate("API", "swap languages"))
        self.language1Label.setText(_translate("API", "language 1:"))
        self.saveButton.setToolTip(_translate("API", "save changes"))
        self.addButton.setToolTip(_translate("API", "add new vocab"))
        self.deleteButton.setToolTip(_translate("API", "delete current vocab"))
        self.language2Label.setText(_translate("API", "language 2:"))
        self.vocabLabel.setText(_translate("API", "Vocabulary"))
        self.informationLabel.setText(_translate("API", "Note: in order for the \"END\" command\n"
"to be properly applied, the application\n"
"must be restarted"))
